name: Build
on:
  pull_request:
    branches: main
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
  
      - name: Build project 🔧
        run: | 
          npm install
          npm run build
          
      - name: Lint 🧹
        run: npm run lint
